# Lint.yml
name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cat ModelFileFinder.swift
        run: cat /Users/runner/work/ModelFileFinder/ModelFileFinder/Sources/ModelFileFinder/ModelFileFinder.swift

      - name: Run SwiftFormat with debugging
        run: |
          swiftformat . --strict --verbose