# Lint.yml
name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Git metadata
        run: |
          echo "Author Name: $(git log -1 --pretty=format:'%an')"
          echo "Author Email: $(git log -1 --pretty=format:'%ae')"
          echo "Commit Date: $(git log -1 --pretty=format:'%ad')"

      - name: Cat file 
        run: 
          cat /Users/runner/work/ModelFileFinder/ModelFileFinder/Tests/ModelFileFinderests/ModelFileFinderTests.swif

      - name: Run SwiftFormat with debugging
        run: |
          swiftformat --lint . --verbose

      - name: Reformat Files
        run: |
          swiftformat .