# Lint.yml
name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean up potential caches
        run: |
          rm -rf .build
          rm -rf .swiftformat.cache

      - name: Print working directory and file details
        run: |
          pwd
          ls -lR
          file *
          find . -type f -exec file {} \;

      - name: Run SwiftFormat with debugging
        run: |
          swiftformat --lint . --verbose

      - name: Reformat Files
        run: |
          swiftformat .